//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEF_FETAL
    {
        public DEF_FETAL()
        {
            this.ACTA_INSCRIPCION = new HashSet<ACTA_INSCRIPCION>();
        }
    
        public int ID_FETAL { get; set; }
        public string ACTAINSCRIPCION { get; set; }
        public string SEXOFETO { get; set; }
        public short SEMANAGESTA { get; set; }
        public System.DateTime FECHADEFUN { get; set; }
        public string PRODUCTOEMBARA { get; set; }
        public string ASISTENCIAFETAL { get; set; }
        public string LUGAROCURRENCIA { get; set; }
        public string NOMBREESTABLEFETAL { get; set; }
        public string PROVINCIAFETAL { get; set; }
        public string CANTONFETAL { get; set; }
        public string PARROQUIAFETAL { get; set; }
        public string LOCALIDADFETAL { get; set; }
        public string CAUSAFETAL { get; set; }
    
        public virtual ICollection<ACTA_INSCRIPCION> ACTA_INSCRIPCION { get; set; }
        public virtual ACTA_INSCRIPCION ACTA_INSCRIPCION1 { get; set; }
    }
}
