//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDICO
    {
        public MEDICO()
        {
            this.ACTA_INSCRIPCION = new HashSet<ACTA_INSCRIPCION>();
        }
    
        public int CI_MEDICO { get; set; }
        public string NOMBREMEDICO { get; set; }
        public int NUMTELEMEDICO { get; set; }
        public byte[] FIRMAMEDICO { get; set; }
        public string OBSERMEDICO { get; set; }
    
        public virtual ICollection<ACTA_INSCRIPCION> ACTA_INSCRIPCION { get; set; }
    }
}
